# Railway Full Stack Deployment
# This includes Grafana, Prometheus, and Bitcoin Exporter

version: '3.8'

services:
  bitcoin-exporter:
    build: 
      context: .
      dockerfile: Dockerfile.railway
    environment:
      - PORT=8000
    expose:
      - "8000"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus-railway.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    expose:
      - "9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - prometheus
