# UI Labels Configuration
dashboard:
  title: "Cryptocurrency Price Monitor"
  subtitle: "Real-time metrics and analysis"
  
panels:
  current_price:
    title: "Current Value"
    unit: "USD"
  
  price_chart:
    title: "Historical Trend"
    legend: "Price over time"
  
  change_percentage:
    title: "24h Change"
    unit: "%"
  
  min_max:
    title: "Daily Range"
    min_label: "Low"
    max_label: "High"
  
  average:
    title: "Average Value"
    description: "Rolling average"
  
  last_update:
    title: "Last Updated"
    format: "YYYY-MM-DD HH:mm:ss"

alerts:
  high_price: "Price exceeded threshold"
  low_price: "Price below threshold"
  connection_error: "Data source unavailable"
